#!/usr/bin/env perl

use strict;
use warnings;

# use FindBin;
# BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use File::Basename 'dirname';
use File::Spec;

push @INC, join('/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib');


# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('WGPA');
